# Generated by Django 2.2.5 on 2019-09-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=200)),
                ('pwd', models.CharField(max_length=200)),
                ('capacity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Volunteer_name', models.CharField(max_length=200)),
                ('Volunteer_address', models.CharField(max_length=200)),
                ('Volunteer_number', models.CharField(max_length=10)),
                ('Volunteer_email', models.CharField(max_length=200)),
                ('Volunteer_pass', models.CharField(max_length=200)),
                ('Volunteer_maxcapacity', models.IntegerField(default=0)),
            ],
        ),
    ]
